export const dataLocal = {
  bestMatches: [
    {
      "symbol": "A",
      "name": "Agilent Technologies Inc",
      "type": "Equity",
      "region": "United States",
      "marketOpen": "09:30",
      "marketClose": "16:00",
      "timezone": "UTC-04",
      "currency": "USD",
      "matchscore": 1,
      "dailyHigh": "136.0500",
      "dailyLow": "129.7800"
    },
    {
      "symbol": "A.TRV",
      "name": "Armor Minerals Inc",
      "type": "Equity",
      "region": "Toronto Venture",
      "marketOpen": "09:30",
      "marketClose": "16:00",
      "timezone": "UTC-05",
      "currency": "CAD",
      "matchscore": 0.5,
      "dailyHigh": "0.4700",
      "dailyLow": "0.4700"
    },
    {
      "symbol": "A02.FRK",
      "name": "Adways Inc",
      "type": "Equity",
      "region": "Frankfurt",
      "marketOpen": "08:00",
      "marketClose": "20:00",
      "timezone": "UTC+02",
      "currency": "EUR",
      "matchscore": 0.3333,
      "dailyHigh": "5.4000",
      "dailyLow": "5.4000"
    },
    {
      "symbol": "A04.FRK",
      "name": "Ascential plc",
      "type": "Equity",
      "region": "Frankfurt",
      "marketOpen": "08:00",
      "marketClose": "20:00",
      "timezone": "UTC+02",
      "currency": "EUR",
      "matchscore": 0.3333,
      "dailyHigh": "2.6200",
      "dailyLow": "2.6200"
    },
    {
      "symbol": "A0T.FRK",
      "name": "American Tower Corp",
      "type": "Equity",
      "region": "Frankfurt",
      "marketOpen": "08:00",
      "marketClose": "20:00",
      "timezone": "UTC+02",
      "currency": "EUR",
      "matchscore": 0.3333,
      "dailyHigh": "267.6500",
      "dailyLow": "267.6000"
    },{
      "symbol": "A16.FRK",
      "name": "ASR Nederland N.V",
      "type": "Equity",
      "region": "Frankfurt",
      "marketOpen": "08:00",
      "marketClose": "20:00",
      "timezone": "UTC+02",
      "currency": "EUR",
      "matchscore": 0.3333,
      "dailyHigh": "42.4400",
      "dailyLow": "42.4400"
    },
    {
      "symbol": "A1A.FRK",
      "name": "Atrium Ljungberg AB (publ)",
      "type": "Equity",
      "region": "Frankfurt",
      "marketOpen": "08:00",
      "marketClose": "20:00",
      "timezone": "UTC+02",
      "currency": "EUR",
      "matchscore": 0.3333,
      "dailyHigh": "14.3200",
      "dailyLow": "14.3200"
    },
    {
      "symbol": "A1B.FRK",
      "name": "Ashmore Group PLC",
      "type": "Equity",
      "region": "Frankfurt",
      "marketOpen": "08:00",
      "marketClose": "20:00",
      "timezone": "UTC+02",
      "currency": "EUR",
      "matchscore": 0.3333,
      "dailyHigh": "2.3600",
      "dailyLow": "2.3600"
    },
    {
      "symbol": "A1AP34.SAO",
      "name": "Advance Auto Parts Inc.",
      "type": "ETF",
      "region": "Brazil/Sao Paolo",
      "marketOpen": "10:00",
      "marketClose": "17:30",
      "timezone": "UTC-03",
      "currency": "BRL",
      "matchscore": 0.2,
      "dailyHigh": "65.9100",
      "dailyLow": "65.9100"
    },
    {
      "symbol": "A1CR34.SAO",
      "name": "Amcor plc",
      "type": "ETF",
      "region": "Brazil/Sao Paolo",
      "marketOpen": "10:00",
      "marketClose": "17:30",
      "timezone": "UTC-03",
      "currency": "BRL",
      "matchscore": 0.2,
      "dailyHigh": "64.1900",
      "dailyLow": "63.5000"
    },
  ],
};
